spring:
  application:
    name: homesync

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/photo_sorter_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:photo_user}
    password: ${SPRING_DATASOURCE_PASSWORD:photo_pass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kafka:
  # Accept SPRING_KAFKA_BOOTSTRAP_SERVERS or KAFKA_BOOTSTRAP_SERVERS (fallback to localhost:9092)
  bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}}

logging:
  level:
    root: INFO
    org.springframework: INFO



# Example (start app with specific env vars):
# SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/photo_sorter_db SPRING_DATASOURCE_USERNAME=photo_user SPRING_DATASOURCE_PASSWORD=photo_pass mvn -pl photo-sorter spring-boot:run
