# This file is loaded when the 'docker' Spring profile is active.
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/photo_sorter_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: photo_user
    password: photo_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true