spring:
  application:
    name: homesync

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:330/photo_sorter_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:photo_user}
    password: ${SPRING_DATASOURCE_PASSWORD:photo_pass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Example (start app with specific env vars):
# SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/photo_sorter_db SPRING_DATASOURCE_USERNAME=photo_user SPRING_DATASOURCE_PASSWORD=photo_pass mvn -pl photo-sorter spring-boot:run
